name: tests

on: [push]

# see https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/Containers/ContainersQuickStart/
jobs:
  cooking:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epicgames/unreal-engine:dev-slim-4.27
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
    
    steps:
      - uses: actions/checkout@v1

      - name: Cook
        run: |
          ls
          mkdir -p "/github/home/Library/Logs/Unreal Engine/LocalBuildLogs"
          ls /github/home/Library/Logs
          ls /github/home/Library/Logs/Unreal Engine
          ls /github/home/Library/Logs/Unreal Engine/LocalBuildLogs
          /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh \
            BuildCookRun                                           \
            -unattended                                            \
            -utf8output                                            \
            -platform=Linux                                        \
            -clientconfig=Shipping                                 \
            -serverconfig=Shipping                                 \
            -project=Chessy.uproject                               \
            -noP4 -nodebuginfo -allmaps                            \
            -cook -build -stage -prereqs -pak -archive             \
            -archivedirectory=Cooked/

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: cooked-chessy-linux
          path: Cooked/*
