name: tests

on: [push]

# see
# https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/Containers/ContainersQuickStart/
jobs:
  cooking:
    runs-on: ghcr.io/epicgames/unreal-engine:dev-4.27
    
    steps:
      - uses: actions/checkout@v1

      - name: Cook
        run: |
          /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh \
            BuildCookRun                                           \
            -utf8output                                            \
            -platform=Linux                                        \
            -clientconfig=Shipping                                 \
            -serverconfig=Shipping                                 \
            -project=cartpole.uproject                             \
            -noP4 -nodebuginfo -allmaps                            \
            -cook -build -stage -prereqs -pak -archive             \
            -archivedirectory=Cooked/

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: cooked-cartpole-linux
          path: Cooked/*
