name: tests

on: [push]

# see https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/Containers/ContainersQuickStart/
jobs:
  cooking:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epicgames/unreal-engine:dev-slim-4.27
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
      
      # For us to be user 1001 else we will be ue4
      # and we wont be able to write anything anywhere
      options: "-u 1001"
    
    steps:
      - uses: actions/checkout@v1

      - name: Cook
        run: |
          pwd       # We are in /__w/Gamekit-Dev/Gamekit-Dev
          # whoami  # We are ue4
                    # 1001 if -u 1001 is passed
                    
          # Our files have a nobody as user
          #
          # drwxr-xr-x  4 1001 121  4096 Jan 29 01:34 Plugins
          # -rw-r--r--  1 1001 121   298 Jan 29 01:34 README.rst
          # drwxr-xr-x  2 1001 121  4096 Jan 29 01:34 Shaders
          # drwxr-xr-x  3 1001 121  4096 Jan 29 01:34 Source
          ls -all
          
          # Permissions are 
          # -rwxr-xr-x 1 ue4 ue4 3336 Dec 10 02:14
          # ls -all /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh
          
          export uebp_LogFolder=./UAT_Logs
          mkdir -p $uebp_LogFolder
          /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh \
            BuildCookRun                                           \
            -unattended                                            \
            -utf8output                                            \
            -platform=Linux                                        \
            -clientconfig=Shipping                                 \
            -serverconfig=Shipping                                 \
            -project=Chessy.uproject                               \
            -noP4 -nodebuginfo -allmaps                            \
            -cook -build -stage -prereqs -pak -archive             \
            -archivedirectory=Cooked/

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: cooked-chessy-linux
          path: Cooked/*
